//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sub1 { get; set; }
        public string Sub2 { get; set; }
        public string Sub3 { get; set; }
        public Nullable<decimal> Mark1 { get; set; }
        public Nullable<decimal> Mark2 { get; set; }
        public Nullable<decimal> Mark3 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Per { get; set; }
    }
}
